server:
  port: 10001
  tomcat:
    connection-timeout: 5000 # unit is ms

logging:
  level:
    root: ERROR
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    ps.demo: DEBUG
  pattern:
    console: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr(${LOGGED_APPLICATION_NAME:-}[%15.15t]){faint} %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

spring:
  application:
    name: springboot-jpa-demo
  profiles:
    active: dev
  mvc:
    async:
      request-timeout: -1
  #      request-timeout: 300000
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolOK

    url: jdbc:h2:mem:springboot-jpa-demo;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
      trace: true
  sql:
    init:
      mode: embedded

springdoc:
  api-docs:
    path: /api-docs


management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, schema

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${JASYPT_PASS}
encpwdtest:
  test1: ENC(C75Umw2KTwzbigkYpl6t4dSxX6H+2jlL)

---

spring:
  config:
    activate:
      on-profile: dev



---

spring:
  config:
    activate:
      on-profile: sit


---

spring:
  config:
    activate:
      on-profile: uat


---

spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      path: /h2-console
      enabled: false