---
apiVersion: v1
kind: Namespace
metadata:
  name: nsapp
  labels:
    namespace: nsapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcloud-gateway
  namespace: nsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springcloud-gateway
  template:
    metadata:
      labels:
        app: springcloud-gateway
    spec:
      containers:
        - name: springcloud-gateway
#          image: "xxx.com/path/repo/springcloud-gateway:20241014-185738"
          image: "springcloud-gateway:20241014-185738"
          ports:
            - containerPort: 10000
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 10000
            initialDelaySeconds: 120
            periodSeconds: 30
          env:
            - name: APPID
              valueFrom:
                secretKeyRef:
                  name: springcloud-gateway-key
                  key: appid
            - name: APPSECRET
              valueFrom:
                secretKeyRef:
                  name: springcloud-gateway-key
                  key: appsecret
          volumeMounts:
            - name: myvolume
              mountPath: /app/volume
              readOnly: true
      volumes:
        - name: myvolume
          secret:
            secretName: springcloud-gateway-key
#            items:
#              - key: key.pem
#                path: key.pem

---
apiVersion: v1
kind: Service
metadata:
  name: springcloud-gateway-service
  namespace: nsapp
  labels:
    app: springcloud-gateway
spec:
  ports:
    - port: 10000 # between containers for service call for K8s
      targetPort: 10000 # container port
      nodePort: 30000 # by default >30000 for external call
  type: NodePort
  selector:
    app: springcloud-gateway

---
apiVersion: v1
kind: Secret
metadata:
  name: springcloud-gateway-key
  namespace: nsapp
type: Opaque
data:
  appid: QVBQMTIzNA==
  appsecret: UGFzc3dkXzEyMzQ1Ng==
  key.pem: VGhpcyBpcyB0aGUgZGF0YSBmcm9tIGtleS5wZW0gZmlsZSBmcm9tIHNlY3JldApnb29kIGx1Y2t+Cl9fa3ViZXJuZXRzIHNlY3JldHM=
